require("dotenv").config();
module.exports = {
  BASE_URL: process.env.BASE_URL,
  FRONTEND_BASE_URL: process.env.FRONTEND_BASE_URL,
  PORT: process.env.PORT,
  USERNAME: process.env.DB_USERNAME,
  PASSWORD: process.env.DB_PASSWORD,
  HOST: process.env.DB_HOST,
  DATABASE: process.env.DB_NAME,
  DIALECT: process.env.DIALECT,
  EMAIL: process.env.MY_EMAIL,
  EMAIL_PASSWORD: process.env.MY_PASSWORD,
  SECRET_KEY: process.env.SECRET_KEY,
  JWT_EXPIRATION: process.env.JWT_EXPIRATION,
  PASSWORD_RESET_EXPIRATION: process.env.PASSWORD_RESET_EXPIRATION,
  JWT_REFRESH_EXPIRATION: process.env.JWT_REFRESH_EXPIRATION,
  DB_URL: process.env.POSTGRES_URL,
  CUSTOM_CSS_URL: process.env.CSS_URL,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  CLOUDINARY_UPLOAD_PRESET: process.env.CLOUDINARY_UPLOAD_PRESET,
  cookieOptions: {
    httpOnly: true,
    secure: true,
    sameSite: "strict",
  },
};
